# Let's jump right in and start looking at some practical SQL

In this exercise we are going to rely on SQLite. This is a small, fast and lightweight SQL variant. In the lecture examples we saw MySQL. All variants of SQL work in a similar way. We chose SQLite for these exercises because of the lightweight profile and the ability to work from a local instance without a complicated setup. 

[Find out more here](https://www.w3resource.com/sqlite/)

In [11]:
import sqlite3 as sql
import pandas as pd

%reload_ext sql

Let's begin by creating a database. The following command will create a local instance of our database with the name dataProgramming.db. If you get an error then check:
- That you have run the above code cell and that the libraries are installed and working on your machine.
- That you have the correct permissions on your local machine.

In [12]:
%sql sqlite:///dataProgramming.db

## Create a table

***%%sql*** let you use multiple SQL statements inside a single cell. 

It is now time to create one using a standard SQL command – CREATE TABLE. If the table already existed in the database, an error will pop up. In addition, we set ***PRIMARY KEY*** on USERID to prevent from inserting duplicate writers into the table.

In [13]:
# %%sql sqlite://
# CREATE TABLE users(
#     FirstName VARCHAR(30) NOT NULL,
#     LastName VARCHAR(30) NOT NULL,  
#     USERID int  NOT NULL UNIQUE, 
#     PRIMARY KEY (USERID)
# );

# Playing with queries
Let's add some users. To find out more about this command, read [here](https://www.w3schools.com/sql/sql_insert.asp) 

Run this code and then try to add four users of your own. What happens if you do not insert data in the NOT NULL fields?

In [14]:
# %%sql sqlite://
# INSERT INTO users VALUES ('Ghulam', 'Baker', 1);
# INSERT INTO users VALUES ('Savannah', 'Shelton', 2);
# You will get an error if you try to run this more than once as there are UNIQUE requirements for these fields.

## Our first query

Let's now try to get some data back. Databases are not all about inserting, in fact queries are more useful. Let's grab all of our data. We can do this by using SELECT and signifying * which is a parameter which indicates all of the columns of a table.

In [20]:
## Fix KeyError: 'DEFAULT'
#%config SqlMagic.autopandas = True
#%config SqlMagic.style = '_DEPRECATED_DEFAULT'
%config SqlMagic.style = 'DEFAULT'

In [21]:
#%config SqlMagic.style = '_DEPRECATED_DEFAULT'
sqlres = %sql SELECT * FROM users
sqlres

 * sqlite:///dataProgramming.db
Done.

  FirstName LastName  USERID
0    Ghulam    Baker       1
1  Savannah  Shelton       2

What about if we want to select just the names of people in the table? In this case we are not concerned with the USERID. Let's have a look at how we might construct such a query.

In [22]:
sqlres = %sql SELECT FirstName, LastName from users
sqlres

 * sqlite:///dataProgramming.db
Done.

  FirstName LastName
0    Ghulam    Baker
1  Savannah  Shelton

In [28]:
''' 
What about if we want to query specific things based on more complex logic? 
Look up Savannah's user ID and put it between the apostrophes in the USERID=''
'''

sqlres = %sql SELECT FirstName FROM users WHERE USERID=2;
sqlres

 * sqlite:///dataProgramming.db
Done.

  FirstName
0  Savannah

In [29]:
# Try to come up with a way to list the columns of a table. There are a few ways that you can do this.

%sql PRAGMA table_info(users);

 * sqlite:///dataProgramming.db
Done.

   cid       name         type  notnull dflt_value  pk
0    0  FirstName  VARCHAR(30)        1       None   0
1    1   LastName  VARCHAR(30)        1       None   0
2    2     USERID          INT        1       None   1

In [30]:
# We can even do mathematical operations inline, for instance we could use the mod function (%) 
# and look for even fields (divisible by 2 where the integer remainder = 0 ie no remainder.)
%sql SELECT USERID FROM users WHERE FirstName='Savannah' and USERID %2 = 0

 * sqlite:///dataProgramming.db
Done.

   USERID
0       2

## Can we rename the table headings from the data we get back from our query? See if you can figure this out using AS

[The AS command](https://www.w3schools.com/sql/sql_ref_as.asp)

In [32]:
# SELECT something AS something FROM somewhere;
%sql SELECT FirstName as name FROM users;

 * sqlite:///dataProgramming.db
Done.

       name
0    Ghulam
1  Savannah

Has the AS command changed the initial data from the table? Run a query on the table to see if it has changed.

In [33]:
%sql SELECT FirstName FROM users;

 * sqlite:///dataProgramming.db
Done.

  FirstName
0    Ghulam
1  Savannah

We saw the '*' parameter earlier, where we pull all of our data back. In some cases these sorts of queries can be really inefficient (and expensive!) One way that we can overcome this is by limiting the number of fields we return. If we combine this with certain types of aggregation we can formalise our queries more effectively.

In [34]:
%sql SELECT * From users LIMIT 1

 * sqlite:///dataProgramming.db
Done.

  FirstName LastName  USERID
0    Ghulam    Baker       1

Try adding an ORDER by parameter to the previous query to further refine our output.
You can find some documentation [here](https://www.w3schools.com/sql/sql_ref_order_by.asp)
HINT: Order first!

In [36]:
%sql SELECT * From users ORDER BY USERID LIMIT 1

 * sqlite:///dataProgramming.db
Done.

  FirstName LastName  USERID
0    Ghulam    Baker       1

In [37]:
# We might even want to get smallest/largest values as follows
%sql SELECT min(USERID), max(USERID) from users

 * sqlite:///dataProgramming.db
Done.

   min(USERID)  max(USERID)
0            1            2

Now see if you can stretch your legs a bit. Experiment with queries using some or all of the following operators.

- 'AND' 
- 'OR'
- 'NOT' 
- 'IN'
- '<>' 
- '!='
- '>=' 
- '>' 
- '<' 
- '<='

Some examples of syntax for each of these parameters can be found [here](https://www.w3schools.com/sql/default.asp). The logic is somewhat similar to the logic you would use in Python.

In [40]:
# how many of these can you use? Can you use all of them in a query?
%sql SELECT LastName FROM users WHERE USERID NOT IN (3,4,5) AND USERID > 0

 * sqlite:///dataProgramming.db
Done.

  LastName
0    Baker
1  Shelton