In [20]:
import csv
with open("data/JIRA_data_shortened.csv") as csvfile:
    reader = csv.reader(csvfile, delimiter=",")
    print(reader)
    for row in reader:
        print(column)

<_csv.reader object at 0x000001F4526953C0>
['Summary', 'Issue key', 'Issue id', 'Issue Type', 'Status', 'Project key', 'Project name', 'Project type', 'Project lead', 'Priority', 'Resolution', 'Assignee', 'Reporter', 'Creator', 'Created', 'Updated', 'Last Viewed', 'Resolved', 'Fix Version/s', 'Votes', 'Labels', 'Labels.1', 'Labels.2', 'Labels.3', 'Labels.4', 'Labels.5', 'Description', 'Watchers', 'Watchers.1', 'Watchers.2', 'Watchers.3', 'Watchers.4', 'Watchers.5', 'Watchers.6', 'Watchers.7', 'Watchers.8', 'Watchers.9', 'Watchers.10', 'Watchers.11', 'Watchers.12', 'Watchers.13', 'Watchers.14', 'Log Work', 'Remaining Estimate', 'Time Spent', 'Î£ Remaining Estimate', 'Î£ Time Spent', 'Inward issue link (Auto - Cascade Incident Resolved )', 'Inward issue link (Auto - Cascade Incident Resolved ).1', 'Inward issue link (Auto - Cascade Incident Resolved ).2', 'Inward issue link (Auto - Cascade Incident Resolved ).3', 'Inward issue link (Auto - Cascade Incident Resolved ).4', 'Inward issue link (Auto - Cascade Incident Resolved ).5', 'Inward issue link (Auto - Cascade Incident Resolved ).6', 'Inward issue link (Auto - Cascade Incident Resolved ).7', 'Inward issue link (Auto - Cascade Incident Resolved ).8', 'Inward issue link (Auto - Cascade Incident Resolved ).9', 'Outward issue link (Auto - Cascade Incident Resolved )', 'Outward issue link (Auto - Cascade Incident Resolved ).1', 'Outward issue link (Auto - Cascade Incident Resolved ).2', 'Inward issue link (Blocks)', 'Inward issue link (Blocks).1', 'Inward issue link (Blocks).2', 'Inward issue link (Blocks).3', 'Inward issue link (Blocks).4', 'Inward issue link (Blocks).5', 'Inward issue link (Blocks).6', 'Inward issue link (Blocks).7', 'Inward issue link (Blocks).8', 'Inward issue link (Blocks).9', 'Inward issue link (Blocks).10', 'Outward issue link (Blocks)', 'Outward issue link (Blocks).1', 'Outward issue link (Blocks).2', 'Outward issue link (Blocks).3', 'Outward issue link (Blocks).4', 'Outward issue link (Blocks).5', 'Outward issue link (Blocks).6', 'Outward issue link (Blocks).7', 'Outward issue link (Blocks).8', 'Inward issue link (Cloners)', 'Inward issue link (Cloners).1', 'Inward issue link (Cloners).2', 'Inward issue link (Cloners).3', 'Inward issue link (Cloners).4', 'Inward issue link (Cloners).5', 'Inward issue link (Cloners).6', 'Outward issue link (Cloners)', 'Outward issue link (Cloners).1', 'Inward issue link (Defect)', 'Inward issue link (Defect).1', 'Inward issue link (Defect).2', 'Inward issue link (Defect).3', 'Inward issue link (Defect).4', 'Inward issue link (Defect).5', 'Inward issue link (Defect).6', 'Inward issue link (Defect).7', 'Inward issue link (Defect).8', 'Inward issue link (Defect).9', 'Inward issue link (Defect).10', 'Inward issue link (Defect).11', 'Outward issue link (Defect)', 'Outward issue link (Defect).1', 'Outward issue link (Defect).2', 'Inward issue link (Duplicate)', 'Inward issue link (Duplicate).1', 'Outward issue link (Duplicate)', 'Inward issue link (Gantt End to End)', 'Inward issue link (Gantt End to End).1', 'Outward issue link (Gantt End to End)', 'Outward issue link (Gantt End to End).1', 'Outward issue link (Gantt End to End).2', 'Inward issue link (Gantt End to Start)', 'Inward issue link (Gantt End to Start).1', 'Inward issue link (Gantt End to Start).2', 'Inward issue link (Gantt End to Start).3', 'Inward issue link (Gantt End to Start).4', 'Inward issue link (Gantt End to Start).5', 'Inward issue link (Gantt End to Start).6', 'Inward issue link (Gantt End to Start).7', 'Outward issue link (Gantt End to Start)', 'Outward issue link (Gantt End to Start).1', 'Outward issue link (Gantt End to Start).2', 'Outward issue link (Gantt End to Start).3', 'Outward issue link (Gantt End to Start).4', 'Outward issue link (Gantt End to Start).5', 'Outward issue link (Gantt End to Start).6', 'Outward issue link (Gantt End to Start).7', 'Outward issue link (Gantt End to Start).8', 'Outward issue link (Gantt End to Start).9', 'Outward issue link (Gantt End to Start).10', 'Inward issue link (Gantt Start to End)', 'Outward issue link (Gantt Start to End)', 'Outward issue link (Gantt Start to End).1', 'Inward issue link (Issue split)', 'Outward issue link (Issue split)', 'Outward issue link (Issue split).1', 'Outward issue link (Issue split).2', 'Inward issue link (Problem/Incident)', 'Inward issue link (Problem/Incident).1', 'Inward issue link (Problem/Incident).2', 'Inward issue link (Problem/Incident).3', 'Inward issue link (Problem/Incident).4', 'Inward issue link (Problem/Incident).5', 'Inward issue link (Problem/Incident).6', 'Outward issue link (Problem/Incident)', 'Outward issue link (Problem/Incident).1', 'Outward issue link (Problem/Incident).2', 'Outward issue link (Problem/Incident).3', 'Outward issue link (Problem/Incident).4', 'Outward issue link (Problem/Incident).5', 'Outward issue link (Problem/Incident).6', 'Outward issue link (Problem/Incident).7', 'Outward issue link (Problem/Incident).8', 'Outward issue link (Problem/Incident).9', 'Outward issue link (Problem/Incident).10', 'Outward issue link (Problem/Incident).11', 'Outward issue link (Problem/Incident).12', 'Outward issue link (Problem/Incident).13', 'Outward issue link (Problem/Incident).14', 'Outward issue link (Problem/Incident).15', 'Outward issue link (Problem/Incident).16', 'Outward issue link (Problem/Incident).17', 'Outward issue link (Problem/Incident).18', 'Outward issue link (Problem/Incident).19', 'Outward issue link (Problem/Incident).20', 'Outward issue link (Problem/Incident).21', 'Outward issue link (Problem/Incident).22', 'Inward issue link (Relates)', 'Inward issue link (Relates).1', 'Inward issue link (Relates).2', 'Inward issue link (Relates).3', 'Inward issue link (Relates).4', 'Inward issue link (Relates).5', 'Inward issue link (Relates).6', 'Inward issue link (Relates).7', 'Inward issue link (Relates).8', 'Inward issue link (Relates).9', 'Outward issue link (Relates)', 'Outward issue link (Relates).1', 'Outward issue link (Relates).2', 'Outward issue link (Relates).3', 'Outward issue link (Relates).4', 'Outward issue link (Relates).5', 'Outward issue link (Relates).6', 'Outward issue link (Relates).7', 'Outward issue link (Relates).8', 'Outward issue link (Relates).9', 'Outward issue link (Relates).10', 'Outward issue link (Relates).11', 'Outward issue link (Relates).12', 'Outward issue link (Relates).13', 'Outward issue link (Relates).14', 'Outward issue link (Relates).15', 'Outward issue link (Relates).16', 'Outward issue link (Relates).17', 'Outward issue link (Relates).18', 'Outward issue link (Relates).19', 'Outward issue link (Relates).20', 'Inward issue link (Releases)', 'Inward issue link (Releases).1', 'Inward issue link (Releases).2', 'Inward issue link (Releases).3', 'Inward issue link (Releases).4', 'Outward issue link (Releases)', 'Outward issue link (Releases).1', 'Outward issue link (Releases).2', 'Inward issue link (Tests)', 'Inward issue link (Tests).1', 'Inward issue link (Tests).2', 'Inward issue link (Tests).3', 'Inward issue link (Tests).4', 'Inward issue link (Tests).5', 'Inward issue link (Tests).6', 'Inward issue link (Tests).7', 'Inward issue link (Tests).8', 'Inward issue link (Tests).9', 'Inward issue link (Tests).10', 'Inward issue link (Tests).11', 'Inward issue link (Tests).12', 'Inward issue link (Tests).13', 'Inward issue link (Tests).14', 'Inward issue link (Tests).15', 'Inward issue link (Tests).16', 'Inward issue link (Tests).17', 'Inward issue link (Tests).18', 'Inward issue link (Tests).19', 'Inward issue link (Tests).20', 'Inward issue link (Tests).21', 'Inward issue link (Tests).22', 'Inward issue link (Tests).23', 'Inward issue link (Tests).24', 'Inward issue link (Tests).25', 'Inward issue link (Tests).26', 'Inward issue link (Tests).27', 'Inward issue link (Tests).28', 'Inward issue link (Tests).29', 'Inward issue link (Tests).30', 'Inward issue link (Tests).31', 'Inward issue link (Tests).32', 'Inward issue link (Tests).33', 'Inward issue link (Tests).34', 'Inward issue link (Tests).35', 'Inward issue link (Tests).36', 'Inward issue link (Tests).37', 'Inward issue link (Tests).38', 'Inward issue link (Tests).39', 'Inward issue link (Tests).40', 'Inward issue link (Tests).41', 'Inward issue link (Tests).42', 'Inward issue link (Tests).43', 'Inward issue link (Tests).44', 'Inward issue link (Tests).45', 'Inward issue link (Tests).46', 'Inward issue link (Tests).47', 'Inward issue link (Tests).48', 'Inward issue link (Tests).49', 'Inward issue link (Tests).50', 'Inward issue link (Tests).51', 'Inward issue link (Tests).52', 'Inward issue link (Tests).53', 'Inward issue link (Tests).54', 'Inward issue link (Tests).55', 'Inward issue link (Tests).56', 'Inward issue link (Tests).57', 'Inward issue link (Tests).58', 'Inward issue link (Tests).59', 'Inward issue link (Tests).60', 'Inward issue link (Tests).61', 'Inward issue link (Tests).62', 'Inward issue link (Tests).63', 'Inward issue link (Tests).64', 'Outward issue link (Tests)', 'Outward issue link (Tests).1', 'Outward issue link (Tests).2', 'Outward issue link (Tests).3', 'Outward issue link (Tests).4', 'Outward issue link (Tests).5', 'Outward issue link (Tests).6', 'Outward issue link (Tests).7', 'Outward issue link (Tests).8', 'Outward issue link (Tests).9', 'Outward issue link (Tests).10', 'Outward issue link (Tests).11', 'Outward issue link (Tests).12', 'Outward issue link (Tests).13', 'Outward issue link (Tests).14', 'Outward issue link (Tests).15', 'Outward issue link (Tests).16', 'Outward issue link (Tests).17', 'Outward issue link (Tests).18', 'Outward issue link (Tests).19', 'Outward issue link (Tests).20', 'Outward issue link (Tests).21', 'Outward issue link (Tests).22', 'Outward issue link (Tests).23', 'Outward issue link (Tests).24', 'Outward issue link (Tests).25', 'Outward issue link (Tests).26', 'Outward issue link (Tests).27', 'Outward issue link (Tests).28', 'Outward issue link (Tests).29', 'Outward issue link (Tests).30', 'Outward issue link (Tests).31', 'Outward issue link (Tests).32', 'Outward issue link (Tests).33', 'Outward issue link (Tests).34', 'Outward issue link (Tests).35', 'Outward issue link (Tests).36', 'Outward issue link (Tests).37', 'Outward issue link (Tests).38', 'Outward issue link (Tests).39', 'Outward issue link (Tests).40', 'Outward issue link (Tests).41', 'Outward issue link (Tests).42', 'Outward issue link (Tests).43', 'Outward issue link (Tests).44', 'Outward issue link (Tests).45', 'Outward issue link (Tests).46', 'Outward issue link (Tests).47', 'Outward issue link (Tests).48', 'Outward issue link (Tests).49', 'Outward issue link (Tests).50', 'Outward issue link (Tests).51', 'Outward issue link (Tests).52', 'Outward issue link (Tests).53', 'Outward issue link (Tests).54', 'Outward issue link (Tests).55', 'Outward issue link (Tests).56', 'Outward issue link (Tests).57', 'Outward issue link (Tests).58', 'Outward issue link (Tests).59', 'Outward issue link (Tests).60', 'Outward issue link (Tests).61', 'Outward issue link (Tests).62', 'Outward issue link (Tests).63', 'Outward issue link (Tests).64', 'Attachment', 'Attachment.1', 'Attachment.2', 'Attachment.3', 'Attachment.4', 'Attachment.5', 'Attachment.6', 'Attachment.7', 'Attachment.8', 'Attachment.9', 'Attachment.10', 'Attachment.11', 'Attachment.12', 'Attachment.13', 'Attachment.14', 'Attachment.15', 'Attachment.16', 'Attachment.17', 'Attachment.18', 'Attachment.19', 'Attachment.20', 'Attachment.21', 'Attachment.22', 'Attachment.23', 'Attachment.24', 'Attachment.25', 'Attachment.26', 'Attachment.27', 'Attachment.28', 'Attachment.29', 'Attachment.30', 'Attachment.31', 'Attachment.32', 'Attachment.33', 'Attachment.34', 'Attachment.35', 'Attachment.36', 'Attachment.37', 'Attachment.38', 'Attachment.39', 'Attachment.40', 'Attachment.41', 'Attachment.42', 'Attachment.43', 'Attachment.44', 'Attachment.45', 'Attachment.46', 'Attachment.47', 'Attachment.48', 'Attachment.49', 'Attachment.50', 'Attachment.51', 'Attachment.52', 'Attachment.53', 'Attachment.54', 'Attachment.55', 'Attachment.56', 'Attachment.57', 'Attachment.58', 'Attachment.59', 'Attachment.60', 'Attachment.61', 'Attachment.62', 'Attachment.63', 'Attachment.64', 'Attachment.65', 'Attachment.66', 'Attachment.67', 'Attachment.68', 'Attachment.69', 'Attachment.70', 'Attachment.71', 'Attachment.72', 'Attachment.73', 'Attachment.74', 'Attachment.75', 'Attachment.76', 'Attachment.77', 'Attachment.78', 'Attachment.79', 'Attachment.80', 'Attachment.81', 'Attachment.82', 'Custom field (Affected Service)', 'Custom field (Affected Service Components)', 'Custom field (Affected Service Components).1', 'Custom field (Affected Service Components).2', 'Custom field (Affected Service Components).3', 'Custom field (Affected Service Components).4', 'Custom field (Affected Service Components).5', 'Custom field (Approvers)', 'Custom field (Approvers).1', 'Custom field (Approvers).2', 'Custom field (Assignment Group)', 'Custom field (Blocking reasons)', 'Custom field (Brand)', 'Custom field (Brand).1', 'Custom field (Brand).2', 'Custom field (Brand).3', 'Custom field (Brand).4', 'Custom field (Brand).5', 'Custom field (Brand).6', 'Custom field (Browsers)', 'Custom field (Browsers).1', 'Custom field (Browsers).2', 'Custom field (Browsers).3', 'Custom field (Business Area)', 'Custom field (Business Area).1', 'Custom field (Business Area).2', 'Custom field (Comments)', 'Custom field (Critical Service test)', 'Custom field (Critical Service test_)', 'Customer Request Type', 'Custom field (Database)', 'Custom field (Date comments)', 'Custom field (Dev start date)', 'Custom field (Developer)', 'Custom field (Developer).1', 'Custom field (Developer).2', 'Custom field (Developer).3', 'Custom field (Developer Lead)', 'Custom field (Environment)', 'Custom field (Environment).1', 'Custom field (Environment).2', 'Custom field (Environment).3', 'Custom field (Epic Link)', 'Custom field (Feature)', 'Custom field (First Commented Date)', 'Custom field (Flagged)', 'Custom field (Go Live Date)', 'Custom field (Go Live Date).1', 'Custom field (INC priority)', 'Custom field (Impact)', 'Custom field (Infrastructure/DevOps)', 'Custom field (Last Reopened User)', 'Custom field (Last Resolution User)', 'Custom field (Last User Commenter)', 'Custom field (Last commented Date)', 'Custom field (Mobile device)', 'Custom field (Networking)', 'Custom field (Pending reason).1', 'Custom field (Platform)', 'Custom field (Platform).1', 'Custom field (Platform).2', 'Custom field (Product)', 'Custom field (Product).1', 'Custom field (Product Manager)', 'Custom field (Product Owner)', 'Custom field (Project Manager)', 'Custom field (QA Start Date)', 'Custom field (QA Tester)', 'Custom field (QA Tester).1', 'Custom field (QA Tester).2', 'Custom field (Rank)', 'Custom field (Reception_Feedback)', 'Custom field (Recipients to Notify)', 'Custom field (Release Link)', 'Custom field (Reported Time)', 'Custom field (Requirement Status)', 'Custom field (Resolution Info)', 'Custom field (Resolution Time Custom Field)', 'Custom field (Scrum Master)', 'Sprint', 'Sprint.1', 'Sprint.2', 'Sprint.3', 'Sprint.4', 'Sprint.5', 'Sprint.6', 'Sprint.7', 'Custom field (Steps to Reproduce)', 'Custom field (Story Points)', 'Custom field (TW start date)', 'Custom field (Target end)', 'Custom field (Target start)', 'Custom field (Team)', 'Custom field (Template for Notification)', 'Custom field (TimeBox)', 'Custom field (Verifiers)', 'Custom field (Year)', 'Custom field (t-shirt)', 'Comment', 'Comment.1', 'Comment.2', 'Comment.3', 'Comment.4', 'Comment.5', 'Comment.6', 'Comment.7', 'Comment.8', 'Comment.9', 'Comment.10', 'Comment.11', 'Comment.12', 'Comment.13', 'Comment.14', 'Comment.15', 'Comment.16', 'Comment.17', 'Comment.18', 'Comment.19', 'Comment.20', 'Comment.21', 'Comment.22', 'Comment.23', 'Comment.24', 'Comment.25', 'Comment.26', 'Comment.27', 'Comment.28', 'Comment.29', 'Comment.30', 'Comment.31', 'Comment.32', 'Comment.33', 'Comment.34', 'Comment.35', 'Comment.36', 'Comment.37', 'Comment.38', 'Comment.39', 'Comment.40', 'Comment.41', 'Comment.42', 'Comment.43', 'Comment.44']

UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 2398: character maps to <undefined>

In [11]:
import pandas as pd

df = pd.read_excel("data/Schools_ParliamentaryConstituencies.xlsx", sheet_name="List of schools")
df.sort_values(by="NO2ug/m3 mean 2013", ascending=True, inplace=True)
df

,URN,Local Authority name,Establisment name,Easting,Northing,Type of Establishment,Phase of education,NO2ug/m3 mean 2013,Above limit,Parliamentary Constituences,Establishment Status,Close Date
3260,142050,Havering,Dycorts School,555075,192641,Academy Special Sponsor Led,Not applicable,22.4,No,Hornchurch and Upminster,Open,NaT
3259,141549,Havering,Drapers' Maylands Primary School,555266,192587,Free Schools,Primary,22.5,No,Hornchurch and Upminster,Open,NaT
3258,131395,Bromley,Browns School,548873,164181,Other Independent Special School,Not applicable,22.8,No,Orpington,Open,NaT
3257,142234,Bromley,Oaklands Primary Academy,541217,159337,Academy Converter,Primary,22.8,No,Orpington,Open,NaT
3256,137414,Havering,Emerson Park Academy,555559,188013,Academy Converter,Secondary,22.9,No,Hornchurch and Upminster,Open,NaT
...,...,...,...,...,...,...,...,...,...,...,...,...
4,101136,Westminster,St Mary's Bryanston Square CofE School,527546,181766,Voluntary Aided School,Primary,67.0,Yes,Cities of London and Westminster,Open,NaT
3,133167,Southwark,London College of Printing & Distributive Trades,531909,178989,Miscellaneous,Not applicable,67.3,Yes,Bermondsey and Old Southwark,Open,NaT
2,100529,Lambeth,DLD College London,530860,179614,Other Independent School,Not applicable,67.8,Yes,Vauxhall,Open,NaT
1,133910,Westminster,London School of Economics and Political Science,530778,181130,Higher Education Institutions,Not applicable,68.2,Yes,Cities of London and Westminster,Open,NaT
0,134154,Tower Hamlets,Courtauld Institute of Art,530773,180770,Higher Education Institutions,Not applicable,73.1,Yes,Cities of London and Westminster,Open,NaT

In [12]:
## Healthcare discussions
df = pd.read_csv("data/estat_tps00152.tsv", delimiter='\t')
df

,"freq,unit,icd10,age,sex,geo\TIME_PERIOD",2011,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,"A,RT,A-R_V-Y,TOTAL,F,AT",817.74,844.98,826.55,795.74,820.93,779.04,797.24,784.67,765.68,819.09,807.4
1,"A,RT,A-R_V-Y,TOTAL,F,BE",840.14,860.63,849.81,799.78,835.59,789,789.61,786.31,759.43,870.67,750.85
2,"A,RT,A-R_V-Y,TOTAL,F,BG",1394.04,1410.57,1309.79,1353.3,1361.1,1300.24,1321.86,1286.24,1261.39,1408.01,1706.98
3,"A,RT,A-R_V-Y,TOTAL,F,CH",724.11,739.4,731.57,700.6,726.05,686.11,685.32,676.42,667.62,720.74,666.47
4,"A,RT,A-R_V-Y,TOTAL,F,CY",909.11,916.04,794.57,845.27,899.62,831.92,904.04,811.5,834.87,841.74,921.6
...,...,...,...,...,...,...,...,...,...,...,...,...
100,"A,RT,A-R_V-Y,TOTAL,T,SE",966.34,975.9,950.13,922.22,926.7,913.05,909.21,897.38,848.12,934.38,849.74
101,"A,RT,A-R_V-Y,TOTAL,T,SI",1099.64,1090.86,1072.08,1018.63,1041.14,1013.64,1014.74,984.96,962.29,1112.42,1050.9
102,"A,RT,A-R_V-Y,TOTAL,T,SK",1471.24,1461.04,1418.12,1353.52,1390.61,1323.93,1335.86,1308.85,1249.35,1365.47,1676.4
103,"A,RT,A-R_V-Y,TOTAL,T,TR",1075.76 d,1060.93 d,1135.98 d,1167 d,1168.38 d,1189.56 d,1182.1 d,1139.43 d,1114.01 d,1304.03 d,1425.61 d
104,"A,RT,A-R_V-Y,TOTAL,T,UK",984.49 d,1008.99,995.65,972.21,1003.64,986.86,983.3,966.59,:,:,:

In [22]:
### Operating systems
import os
import shutil
os.name

'nt'

In [27]:
filename = "secretCodes.txt"
print(os.path.join('./',filename))

./secretCodes.txt

In [29]:
# current working directory
os.getcwd()

'C:\\Users\\kuszk\\Documents\\Visual Studio 2019\\Python'

In [33]:
shutil.rmtree('test')
os.mkdir("test")

In [38]:
os.chdir("/Users/kuszk/")
os.getcwd()
os.chdir('C:\\Users\\kuszk\\Documents\\Visual Studio 2019\\Python')
os.getcwd()

'C:\\Users\\kuszk\\Documents\\Visual Studio 2019\\Python'

In [39]:
if os.path.exists("demofile.txt"):
    os.remove("demofile.txt")
else:
    print("the file doesn't exist")

the file doesn't exist

In [43]:
try:
    shutil.rmtree('temp')
except OSError as e:
    print("Error: %s - %s." % (e.filename, e.strerror))

Error: temp - The system cannot find the path specified.

In [44]:
# absoluth path:
os.getcwd()

'C:\\Users\\kuszk\\Documents\\Visual Studio 2019\\Python'

In [46]:
# relative path: x -> y
os.path.abspath('..')

'C:\\Users\\kuszk\\Documents\\Visual Studio 2019'

In [51]:
cd = os.path.relpath('..','/')
cd

'Users\\kuszk\\Documents\\Visual Studio 2019'

In [54]:
os.path.getsize(os.getcwd())

4096

In [58]:
import sys
thisfile = sys.argv[0]
thisfile
os.path.getsize(thisfile)

512

In [60]:
os.getcwd()

'C:\\Users\\kuszk\\Documents\\Visual Studio 2019\\Python'

In [62]:
f = open('answers.txt', 'r')
answers = f.read()
print(answers)
f.close()

exam answers
24
4
14

In [63]:
## os.walk is very useful
os.chdir('./data/')
for root, dirs, files in os.walk("."):
    for name in files:
        print(os.path.join(root, name))
    for name in dirs:
        print(os.path.join(root, name))

.\animals.txt
.\estat_tps00152.tsv
.\estat_tps00165.tsv
.\Jira 2024-09-26T17_11_06-0500.csv
.\JIRA_data.csv
.\JIRA_data_shortened.csv
.\Schools_ParliamentaryConstituencies - Copy.xlsx
.\Schools_ParliamentaryConstituencies.xlsx
.\Tableau.twb
.\.ipynb_checkpoints
.\JIRA
.\.ipynb_checkpoints\animals-checkpoint.txt
.\.ipynb_checkpoints\NLP-checkpoint.ipynb

### Pandas

In [3]:
import pandas as pd
import numpy as np

data = pd.DataFrame(np.arange(16).reshape((4,4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two','three','four'])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [20]:
data.loc['Ohio']  ## Sor, oszlop

one      0
two      1
three    2
four     3
Name: Ohio, dtype: int64

In [41]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.loc[:,'d']
series

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [38]:
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0