In [19]:
# First, import packages and load some data
import pandas      as pd
import numpy       as np
import scipy       as sp
import scipy.stats as stats

datafile = './pima-indians-diabetes.csv'

df = pd.read_csv(datafile, header=0, index_col=None)
df.describe()

,times_pregnant,plasma_glucose_concentration,diastolic_blood_pressure,triceps_thickness,2-hour_serum_insulin,BMI,diabetes_pedigreen,age,diabetes
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [3]:
# Check if there is any NaN
df.isna().sum()

times_pregnant                  0
plasma_glucose_concentration    0
diastolic_blood_pressure        0
triceps_thickness               0
2-hour_serum_insulin            0
BMI                             0
diabetes_pedigreen              0
age                             0
diabetes                        0
dtype: int64

In [ ]:
df_nan = df.copy()

# Convert to float to avoid type mismatch with NaN
df_nan.iloc[:, 1:8] = df_nan.iloc[:, 1:8].astype(float)

# Replace 0 to NAN
df_nan.iloc[:, 1:8] = df_nan.iloc[:, 1:8].replace({0: np.nan})

In [5]:
df_nan

,times_pregnant,plasma_glucose_concentration,diastolic_blood_pressure,triceps_thickness,2-hour_serum_insulin,BMI,diabetes_pedigreen,age,diabetes
0,6,148.0,72.0,35.0,NaN,33.6,0.627,50.0,1
1,1,85.0,66.0,29.0,NaN,26.6,0.351,31.0,0
2,8,183.0,64.0,NaN,NaN,23.3,0.672,32.0,1
3,1,89.0,66.0,23.0,94.0,28.1,0.167,21.0,0
4,0,137.0,40.0,35.0,168.0,43.1,2.288,33.0,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76.0,48.0,180.0,32.9,0.171,63.0,0
764,2,122.0,70.0,27.0,NaN,36.8,0.340,27.0,0
765,5,121.0,72.0,23.0,112.0,26.2,0.245,30.0,0
766,1,126.0,60.0,NaN,NaN,30.1,0.349,47.0,1
767,1,93.0,70.0,31.0,NaN,30.4,0.315,23.0,0

In [6]:
# Check counf of NaN values / columns
df_nan.isna().sum()

times_pregnant                    0
plasma_glucose_concentration      5
diastolic_blood_pressure         35
triceps_thickness               227
2-hour_serum_insulin            374
BMI                              11
diabetes_pedigreen                0
age                               0
diabetes                          0
dtype: int64

In [7]:
# Check count of 0 values / columns
(df_nan == 0).sum()

times_pregnant                  111
plasma_glucose_concentration      0
diastolic_blood_pressure          0
triceps_thickness                 0
2-hour_serum_insulin              0
BMI                               0
diabetes_pedigreen                0
age                               0
diabetes                        500
dtype: int64

In [8]:
def print_stats(df):
    for col in df.columns:
        col_min  = np.min(df[col])
        col_max = np.max(df[col])
        col_mean = np.nanmean(df[col])
        col_median = np.nanmedian(df[col])
        freq = stats.mode(df[col])
        print(f"{col}:\nmin:{col_min}, max:{col_max}, mean:{col_mean}, median:{col_median}, mode:{freq.mode} count:{freq.count}\n")

In [9]:
print_stats(df_nan)

times_pregnant:
min:0, max:17, mean:3.8450520833333335, median:3.0, mode:1 count:135

plasma_glucose_concentration:
min:44.0, max:199.0, mean:121.6867627785059, median:117.0, mode:99.0 count:17

diastolic_blood_pressure:
min:24.0, max:122.0, mean:72.40518417462484, median:72.0, mode:70.0 count:57

triceps_thickness:
min:7.0, max:99.0, mean:29.153419593345657, median:29.0, mode:nan count:227

2-hour_serum_insulin:
min:14.0, max:846.0, mean:155.5482233502538, median:125.0, mode:nan count:374

BMI:
min:18.2, max:67.1, mean:32.457463672391015, median:32.3, mode:32.0 count:13

diabetes_pedigreen:
min:0.078, max:2.42, mean:0.47187630208333325, median:0.3725, mode:0.254 count:6

age:
min:21.0, max:81.0, mean:33.240885416666664, median:29.0, mode:22.0 count:72

diabetes:
min:0, max:1, mean:0.3489583333333333, median:0.0, mode:0 count:500

In [11]:
# Hint: centre([0,1,2,3,5,10]) => [-1.059, -0.757, -0.454, -0.151, 0.454, 1.967]
def centre_population(v):
    v = (v - np.nanmean(v)) / np.nanstd(v)
    return v

# Let's see if there is any difference if we calculate the std with the sample's formula (N-1)
def centre_sample(v):
    v = (v - np.nanmean(v)) / np.nanstd(v, ddof=1)
    return v

# test
centre_population([0,1,2,3,5,10])

array([-1.05930987, -0.75664991, -0.45398995, -0.15132998,  0.45398995,
        1.96728976])

In [12]:
# Let's make a copy of df, to hold the centred values:
cdf_pop = df_nan.copy()
cdf_sample = df_nan.copy()

In [13]:
# Now fill in cdf by applying your centre() function to each column in df
cdf_pop = cdf_pop.apply(centre_population, axis=0)
cdf_sample = cdf_sample.apply(centre_sample, axis=0)

In [14]:
# Finally! Let's look for outliers by getting the min and max in the new centred df
# Let's see if there is any difference in the result using population / sample std
print_stats(cdf_pop)
print("----------------")
print_stats(cdf_sample)

times_pregnant:
min:-1.1418515161634994, max:3.906578350084603, mean:-6.47630097698008e-17, median:-0.2509521280020695, mode:-0.8448850534430228 count:135

plasma_glucose_concentration:
min:-2.5458028356433275, max:2.5335623665052704, mean:1.0709359713291156e-16, median:-0.15358567592172978, mode:-0.7434474413325347 count:17

diastolic_blood_pressure:
min:-3.9119381063119154, max:4.008079985872919, mean:-4.87104672195703e-16, median:-0.03274557136424161, mode:-0.194378593653728 count:57

triceps_thickness:
min:-2.116441714620514, max:6.672839638745545, mean:-3.4476426642703566e-17, median:-0.014657043163412858, mode:nan count:227

2-hour_serum_insulin:
min:-1.1932407938588772, max:5.820456142725143, mean:1.1271299742387376e-17, median:-0.25751920736749945, mode:nan count:374

BMI:
min:-2.0602042070654236, max:5.005848215749845, mean:3.660656102330767e-16, median:-0.02275350846224823, mode:-0.06610352332614518 count:13

diabetes_pedigreen:
min:-1.1895531764897842, max:5.88356476587794, mean:2.4517425127138875e-16, median:-0.3001282260084456, mode:-0.6580122892751302 count:6

age:
min:-1.0415494364835023, max:4.063715751598595, mean:1.9313254699208451e-16, median:-0.3608474114058894, mode:-0.9564616833488008 count:72

diabetes:
min:-0.732120208708925, max:1.3658959117703826, mean:7.401486830834377e-17, median:-0.732120208708925, mode:-0.732120208708925 count:500

----------------
times_pregnant:
min:-1.1411078811017759, max:3.9040341763532815, mean:-7.864079757761526e-17, median:-0.2507886944920598, mode:-0.8443348188985371 count:135

plasma_glucose_concentration:
min:-2.5441340037133227, max:2.5319015584824784, mean:1.2804669222413338e-16, median:-0.15348499700175175, mode:-0.7429600945470706 count:17

diastolic_blood_pressure:
min:-3.90926875212438, max:4.00534502821165, mean:-5.161855481476853e-16, median:-0.032723227061834746, mode:-0.19424595727277413 count:57

triceps_thickness:
min:-2.1144847639342457, max:6.666669651629816, mean:-4.268509965287108e-17, median:-0.014643490647187554, mode:nan count:227

2-hour_serum_insulin:
min:-1.191725566842764, max:5.813065084324401, mean:1.5779819639342328e-17, median:-0.25719219871829846, mode:nan count:374

BMI:
min:-2.058842988411981, max:5.002540750429556, mean:3.637190358085057e-16, median:-0.02273847475828633, mode:-0.0660598473892156 count:13

diabetes_pedigreen:
min:-1.1887784755437325, max:5.879733072364472, mean:2.4517425127138875e-16, median:-0.2999327663810655, mode:-0.6575837563157888 count:6

age:
min:-1.0408711235255357, max:4.061069241548041, mean:2.0354088784794536e-16, median:-0.36061240818239215, mode:-0.9558387841076428 count:72

diabetes:
min:-0.7316434126904535, max:1.3650063669598014, mean:4.163336342344337e-17, median:-0.7316434126904535, mode:-0.7316434126904535 count:500

In [18]:
# trick question:
# What is the mean of cdf['times_pregnant']?
np.nanmean(cdf_pop['times_pregnant'])

np.float64(-6.47630097698008e-17)

<u>Why isn't it zero?</u>

It's technicall zero: −0.0000000000000000647630097698008
Computers can't fully represent floating-point numbers (which might even be infinite), so it is likely due to rounding inaccuracies.